//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ---------------- Integer Types Definitions -----------------

typedef int64_t int33_t;
typedef int64_t int128_t;

// ------------------- Function Prototypes --------------------

int32_t __clang_call_terminate(void);
int32_t __cxx_global_var_init(void);
int32_t __do_global_dtors_aux(void);
int32_t _fini(void);
int32_t _GLOBAL__sub_I_test_cpp(void);
int32_t _init(void);
int32_t _start(int32_t a1);
int32_t _Z10updateKeysiPiS_ii(int32_t a1, int32_t * a2, int32_t * a3, int32_t a4, int32_t a5);
int32_t _Z15controlFlowTesti(int32_t a1);
int32_t _Z3fooii(int32_t a1, int32_t a2);
int32_t _Z5test2i(int32_t a1);
int32_t _Z5test3NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE(int32_t a1);
int32_t _Z5test4iii(int32_t a1, int32_t a2, int32_t a3);
int32_t _Z5test5iii(int32_t a1, int32_t a2, int32_t a3);
int32_t _Z7encryptPii(int32_t * a1, int32_t a2);
int32_t _Z8test_strv(void);
int32_t _Z9print_strPKc(char * a1);
int32_t _ZN9__gnu_cxx11char_traitsIcE2eqERKcS3_(char * a1, char * a2);
int32_t _ZN9__gnu_cxx11char_traitsIcE6lengthEPKc(char * a1);
bool _ZN9__gnu_cxx17__is_null_pointerIKcEEbPT_(char * a1);
int32_t _ZNSt11char_traitsIcE6lengthEPKc(char * a1);
int32_t _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_Alloc_hiderD2Ev(void);
void _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPKcEEvT_S8_St20forward_iterator_tag(char * a1, char * a2, int32_t a3);
int32_t _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC2IS3_EEPKcRKS3_(char * a1, int32_t * a2);
int32_t _ZSt10__distanceIPKcENSt15iterator_traitsIT_E15difference_typeES3_S3_St26random_access_iterator_tag(char * a1, char * a2, int32_t a3);
int32_t _ZSt19__iterator_categoryIPKcENSt15iterator_traitsIT_E17iterator_categoryERKS3_(char ** a1);
int32_t _ZSt8distanceIPKcENSt15iterator_traitsIT_E15difference_typeES3_S3_(char * a1, char * a2);
bool _ZSteqIcSt11char_traitsIcESaIcEEbRKNSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_(int32_t * a1, char * a2);
int32_t _ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EERKS8_SA_(int32_t * a1, int32_t * a2);
int32_t deregister_tm_clones(void);
int32_t frame_dummy(void);
int32_t function_2030(void);
int32_t function_2040(void);
int32_t function_2050(void);
int32_t function_2060(void);
int32_t function_2070(void);
int32_t function_2080(void);
int32_t function_2090(void);
int32_t function_20a0(void);
int32_t function_20b0(void);
int32_t function_20c0(void);
int32_t function_20d0(void);
int32_t function_20e0(void);
int32_t function_20f0(void);
int32_t function_2100(void);
int32_t function_2110(void);
int32_t function_2120(void);
int32_t function_2130(void);
int32_t function_2140(void);
int32_t function_2150(void);
int32_t function_2160(void);
int32_t function_2170(void);
int32_t function_2180(void);
int32_t function_2190(void);
int32_t function_21a0(void);
int32_t function_21b0(void);
int32_t function_21c0(void);
int32_t function_21d0(void);
int32_t function_21e0(void);
int32_t function_21f0(void);
int32_t function_2200(void);
int32_t function_2210(void);
int32_t function_2220(void);
int32_t function_2230(void);
int32_t function_2240(void);
int32_t function_2250(void);
int32_t function_2771(void);
int32_t function_2788(void);
int32_t function_279d(void);
int32_t function_2fcd(void);
int32_t function_2fe1(void);
int32_t function_2ff5(void);
int32_t function_301c(void);
int32_t function_3073(void);
int32_t function_30a2(void);
int32_t function_30ae(void);
int32_t function_30b8(void);
int32_t function_30c0(void);
int32_t function_3140(void);
int32_t function_3150(void);
int32_t function_3160(void);
int32_t function_3190(void);
int32_t function_3275(void);
int32_t register_tm_clones(void);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------------------------ Functions -------------------------

// Address range: 0x2000 - 0x201b
int32_t _init(void) {
    // 0x2000
    return *(int32_t *)0x3fd9 - 2;
}

// Address range: 0x2030 - 0x2036
int32_t function_2030(void) {
    // 0x2030
    int32_t result; // 0x2030
    return result;
}

// Address range: 0x2040 - 0x2046
int32_t function_2040(void) {
    // 0x2040
    int32_t result; // 0x2040
    return result;
}

// Address range: 0x2050 - 0x2056
int32_t function_2050(void) {
    // 0x2050
    int32_t result; // 0x2050
    return result;
}

// Address range: 0x2060 - 0x2066
int32_t function_2060(void) {
    // 0x2060
    int32_t result; // 0x2060
    return result;
}

// Address range: 0x2070 - 0x2076
int32_t function_2070(void) {
    // 0x2070
    int32_t result; // 0x2070
    return result;
}

// Address range: 0x2080 - 0x2086
int32_t function_2080(void) {
    // 0x2080
    int32_t result; // 0x2080
    return result;
}

// Address range: 0x2090 - 0x2096
int32_t function_2090(void) {
    // 0x2090
    int32_t result; // 0x2090
    return result;
}

// Address range: 0x20a0 - 0x20a6
int32_t function_20a0(void) {
    // 0x20a0
    int32_t result; // 0x20a0
    return result;
}

// Address range: 0x20b0 - 0x20b6
int32_t function_20b0(void) {
    // 0x20b0
    int32_t result; // 0x20b0
    return result;
}

// Address range: 0x20c0 - 0x20c6
int32_t function_20c0(void) {
    // 0x20c0
    int32_t result; // 0x20c0
    return result;
}

// Address range: 0x20d0 - 0x20d6
int32_t function_20d0(void) {
    // 0x20d0
    int32_t result; // 0x20d0
    return result;
}

// Address range: 0x20e0 - 0x20e6
int32_t function_20e0(void) {
    // 0x20e0
    int32_t result; // 0x20e0
    return result;
}

// Address range: 0x20f0 - 0x20f6
int32_t function_20f0(void) {
    // 0x20f0
    int32_t result; // 0x20f0
    return result;
}

// Address range: 0x2100 - 0x2106
int32_t function_2100(void) {
    // 0x2100
    int32_t result; // 0x2100
    return result;
}

// Address range: 0x2110 - 0x2116
int32_t function_2110(void) {
    // 0x2110
    int32_t result; // 0x2110
    return result;
}

// Address range: 0x2120 - 0x2126
int32_t function_2120(void) {
    // 0x2120
    int32_t result; // 0x2120
    return result;
}

// Address range: 0x2130 - 0x2136
int32_t function_2130(void) {
    // 0x2130
    int32_t result; // 0x2130
    return result;
}

// Address range: 0x2140 - 0x2146
int32_t function_2140(void) {
    // 0x2140
    int32_t result; // 0x2140
    return result;
}

// Address range: 0x2150 - 0x2156
int32_t function_2150(void) {
    // 0x2150
    int32_t result; // 0x2150
    return result;
}

// Address range: 0x2160 - 0x2166
int32_t function_2160(void) {
    // 0x2160
    int32_t result; // 0x2160
    return result;
}

// Address range: 0x2170 - 0x2176
int32_t function_2170(void) {
    // 0x2170
    int32_t result; // 0x2170
    return result;
}

// Address range: 0x2180 - 0x2186
int32_t function_2180(void) {
    // 0x2180
    int32_t result; // 0x2180
    return result;
}

// Address range: 0x2190 - 0x2196
int32_t function_2190(void) {
    // 0x2190
    int32_t result; // 0x2190
    return result;
}

// Address range: 0x21a0 - 0x21a6
int32_t function_21a0(void) {
    // 0x21a0
    int32_t result; // 0x21a0
    return result;
}

// Address range: 0x21b0 - 0x21b6
int32_t function_21b0(void) {
    // 0x21b0
    int32_t result; // 0x21b0
    return result;
}

// Address range: 0x21c0 - 0x21c6
int32_t function_21c0(void) {
    // 0x21c0
    int32_t result; // 0x21c0
    return result;
}

// Address range: 0x21d0 - 0x21d6
int32_t function_21d0(void) {
    // 0x21d0
    int32_t result; // 0x21d0
    return result;
}

// Address range: 0x21e0 - 0x21e6
int32_t function_21e0(void) {
    // 0x21e0
    int32_t result; // 0x21e0
    return result;
}

// Address range: 0x21f0 - 0x21f6
int32_t function_21f0(void) {
    // 0x21f0
    int32_t result; // 0x21f0
    return result;
}

// Address range: 0x2200 - 0x2206
int32_t function_2200(void) {
    // 0x2200
    int32_t result; // 0x2200
    return result;
}

// Address range: 0x2210 - 0x2216
int32_t function_2210(void) {
    // 0x2210
    int32_t result; // 0x2210
    return result;
}

// Address range: 0x2220 - 0x2226
int32_t function_2220(void) {
    // 0x2220
    int32_t result; // 0x2220
    return result;
}

// Address range: 0x2230 - 0x2236
int32_t function_2230(void) {
    // 0x2230
    int32_t result; // 0x2230
    return result;
}

// Address range: 0x2240 - 0x2246
int32_t function_2240(void) {
    // 0x2240
    int32_t result; // 0x2240
    return result;
}

// Address range: 0x2250 - 0x2256
int32_t function_2250(void) {
    // 0x2250
    int32_t result; // 0x2250
    return result;
}

// Address range: 0x2260 - 0x228c
int32_t __cxx_global_var_init(void) {
    // 0x2260
    function_21d0();
    return function_2100();
}

// Address range: 0x2290 - 0x229b
int32_t _GLOBAL__sub_I_test_cpp(void) {
    // 0x2290
    return __cxx_global_var_init();
}

// Address range: 0x22a0 - 0x22c6
int32_t _start(int32_t a1) {
    // 0x22a0
    int32_t v1; // 0x22a0
    int32_t v2 = v1 - 2; // 0x22ad
    int32_t v3 = v2; // bp-4, 0x22b1
    __asm_hlt(&v3, v2);
    // UNREACHABLE
}

// Address range: 0x22d0 - 0x22f9
int32_t deregister_tm_clones(void) {
    // 0x22d0
    return *(int32_t *)0x3cf6 - 1;
}

// Address range: 0x2300 - 0x2339
int32_t register_tm_clones(void) {
    // 0x2300
    return *(int32_t *)0x3cc5 - 1;
}

// Address range: 0x2340 - 0x2379
int32_t __do_global_dtors_aux(void) {
    // 0x2340
    int32_t result; // 0x2340
    if (*(char *)0x3df5 != 0) {
        // 0x2378
        return result;
    }
    if (result != 2) {
        // 0x235b
        function_2250();
    }
    int32_t result2 = deregister_tm_clones(); // 0x2367
    *(char *)0x3dcd = 1;
    return result2;
}

// Address range: 0x2380 - 0x2389
int32_t frame_dummy(void) {
    // 0x2380
    return register_tm_clones();
}

// Address range: 0x2390 - 0x23c2
// Demangled:     foo(int, int)
int32_t _Z3fooii(int32_t a1, int32_t a2) {
    // 0x2390
    int32_t result; // 0x2390
    int32_t v1; // 0x2390
    if (v1 > 0) {
        uint32_t v2 = v1 - 1;
        result = v2 + v1 + (int32_t)((int33_t)v2 * (int33_t)(v1 - 2) / 2);
    }
    // 0x23bd
    return result;
}

// Address range: 0x23d0 - 0x242a
// Demangled:     encrypt(int*, int)
int32_t _Z7encryptPii(int32_t * a1, int32_t a2) {
    // 0x23d0
    int32_t v1; // 0x23d0
    if (v1 <= 15) {
        // 0x2425
        return -1;
    }
    int16_t v2 = 0; // 0x2417
    int32_t result = 0; // 0x240e
    __asm_arpl(v2, (int16_t)v1);
    result += *(int32_t *)(v1 - 1 + 4 * v1);
    v2++;
    int32_t v3 = v2; // 0x23f8
    while (v1 > v3) {
        // 0x2400
        __asm_arpl(v2, (int16_t)v1);
        result = result + v3 + *(int32_t *)(v1 - 1 + 4 * v1);
        v2++;
        v3 = v2;
    }
    // 0x2425
    return result;
}

// Address range: 0x2430 - 0x2530
// Demangled:     test2(int)
int32_t _Z5test2i(int32_t a1) {
    // 0x2430
    function_2210();
    _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC2IS3_EEPKcRKS3_((char *)&g1, &g1);
    function_2160();
    function_2120();
    bool v1 = _ZSteqIcSt11char_traitsIcESaIcEEbRKNSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_(&g1, (char *)&g1); // 0x24de
    function_20b0();
    return v1 ? 99 : 199;
}

// Address range: 0x2530 - 0x2700
// Demangled:     controlFlowTest(int)
int32_t _Z15controlFlowTesti(int32_t a1) {
    // 0x2530
    int32_t v1; // 0x2530
    uint32_t v2 = v1;
    __asm_arpl((int16_t)v2, (int16_t)v1);
    int32_t v3 = 0x55555556 * v1; // 0x2542
    int32_t v4 = v1 - 4 + -3 * (v3 | (int32_t)(v3 < 0)); // 0x255a
    function_2210();
    _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC2IS3_EEPKcRKS3_((char *)&g1, &g1);
    function_2160();
    int32_t v5; // 0x2530
    if (v4 != 0) {
        if (v4 != 1) {
            // 0x2604
            function_21b0();
            v5 = v2 - 5;
        } else {
            // 0x25e7
            function_21b0();
            v5 = v2 + 10;
        }
    } else {
        // 0x2591
        function_21b0();
        v5 = 2 * v2;
    }
    // 0x2623
    _ZSteqIcSt11char_traitsIcESaIcEEbRKNSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_(&g1, (char *)&g1);
    int32_t v6 = 100; // 0x2655
    if (v5 > 19) {
        // 0x2666
        v6 = v5 > 29 ? 300 : 200;
    }
    int32_t v7 = 0; // 0x2698
    int32_t v8 = 0; // 0x2698
    if (v2 <= 0) {
        // 0x26cd
        function_20b0();
        return v5 - 1 + v6;
    }
    int64_t v9 = 0;
    v8 += (v7 << (int32_t)((0x100000000 * v9 | v9) % 2 == 0));
    v7++;
    int32_t v10 = v8; // 0x2698
    while (v7 != v2) {
        // 0x269a
        v9 = v7;
        v8 += (v7 << (int32_t)((0x100000000 * v9 | v9) % 2 == 0));
        v7++;
        v10 = v8;
    }
    // 0x26cd
    function_20b0();
    return v5 - 1 + v6 + v10;
}

// Address range: 0x2700 - 0x2771
// Demangled:     test3(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
int32_t _Z5test3NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE(int32_t a1) {
    // 0x2700
    function_2210();
    _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC2IS3_EEPKcRKS3_((char *)&g1, &g1);
    function_2160();
    _ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EERKS8_SA_(&g1, &g1);
    function_20b0();
    int32_t v1; // 0x2700
    return v1 - 2;
}

// Address range: 0x2771 - 0x2788
int32_t function_2771(void) {
    // 0x2771
    int32_t v1; // 0x2771
    *(int32_t *)(v1 - 64) = v1 - 1;
    *(int32_t *)(v1 - 68) = v1 - 1;
    function_2160();
    return function_279d();
}

// Address range: 0x2788 - 0x279d
int32_t function_2788(void) {
    // 0x2788
    int32_t v1; // 0x2788
    *(int32_t *)(v1 - 64) = v1 - 1;
    *(int32_t *)(v1 - 68) = v1 - 1;
    return function_20b0();
}

// Address range: 0x279d - 0x27b0
int32_t function_279d(void) {
    // 0x279d
    return function_2200();
}

// Address range: 0x27b0 - 0x2809
// Demangled:     updateKeys(int, int*, int*, int, int)
int32_t _Z10updateKeysiPiS_ii(int32_t a1, int32_t * a2, int32_t * a3, int32_t a4, int32_t a5) {
    // 0x27b0
    int32_t v1; // 0x27b0
    int32_t result = v1 - 3; // 0x27bb
    if (v1 != 0) {
        // 0x2807
        return result;
    }
    // 0x27d5
    if (v1 <= 0) {
        // 0x2807
        return 0;
    }
    int16_t v2 = v1; // 0x27e2
    int32_t v3 = 4 * v1 - 1;
    int32_t * v4 = (int32_t *)(v3 + v1);
    int16_t v5 = 0; // 0x27ff
    __asm_arpl(v5, v2);
    __asm_arpl((int16_t)*(int32_t *)(v3 + v1), v2);
    *v4 = *v4 ^ result;
    v5++;
    int32_t result2 = v5; // 0x27d5
    while (v1 > result2) {
        // 0x27dd
        __asm_arpl(v5, v2);
        __asm_arpl((int16_t)*(int32_t *)(v3 + v1), v2);
        *v4 = *v4 ^ result;
        v5++;
        result2 = v5;
    }
    // 0x2807
    return result2;
}

// Address range: 0x2810 - 0x2848
// Demangled:     test4(int, int, int)
int32_t _Z5test4iii(int32_t a1, int32_t a2, int32_t a3) {
    // 0x2810
    int32_t v1; // 0x2810
    int32_t v2 = v1;
    int32_t v3 = 2 * v1; // 0x2827
    return v3 > v2 ? v2 - 10 : v3;
}

// Address range: 0x2850 - 0x29a4
// Demangled:     test5(int, int, int)
int32_t _Z5test5iii(int32_t a1, int32_t a2, int32_t a3) {
    // 0x2850
    int32_t v1; // 0x2850
    int32_t v2 = v1;
    int32_t v3 = 2 * v1; // 0x2877
    int32_t v4 = v2 + v3; // 0x28a5
    int32_t v5 = v1 + 10 + v2;
    int32_t v6; // 0x2850
    for (int32_t i = 0; i < 100; i++) {
        int32_t v7 = (v3 > v2 ? v2 - 10 : v3) + 10 + i; // 0x2899
        int32_t v8 = i + 120 + (v7 < v4 ? v5 : v7 - v4); // 0x28d2
        int32_t v9 = i + 130 + (v8 < v4 ? v5 : v8 - v4); // 0x290d
        int32_t v10 = v9 < v4 ? v5 : v9 - v4;
        v6 = v10;
        switch (i) {
            case 0: {
                // 0x2969
                v6 = v10 + 333;
                // break -> 0x2992
                break;
            }
            case 11: {
                // 0x2976
                v6 = v10 + 222;
                // break -> 0x2992
                break;
            }
            case 12: {
                // 0x2983
                v6 = v10 + 111;
                // break -> 0x2992
                break;
            }
        }
    }
    // 0x299c
    return v6 + 10;
}

// Address range: 0x29b0 - 0x29d4
// Demangled:     print_str(char const*)
int32_t _Z9print_strPKc(char * a1) {
    // 0x29b0
    return function_2030() - 1;
}

// Address range: 0x29e0 - 0x2cc0
// Demangled:     test_str()
int32_t _Z8test_strv(void) {
    // 0x29e0
    function_20a0();
    function_3190();
    function_20a0();
    function_3190();
    _Z9print_strPKc((char *)&g1);
    _Z9print_strPKc((char *)&g1);
    function_20a0();
    function_3160();
    _Z9print_strPKc((char *)&g1);
    function_20a0();
    function_3150();
    _Z9print_strPKc((char *)&g1);
    function_20a0();
    function_30c0();
    function_20a0();
    function_3140();
    return function_2190() - 1;
}

// Address range: 0x2cc0 - 0x2fcd
int main(int argc, char ** argv) {
    // 0x2cc0
    int128_t v1; // 0x2cc0
    int128_t v2 = v1;
    int128_t v3 = __asm_xorps(v2, v2); // 0x2cd2
    __asm_movaps(v3);
    __asm_movaps(v3);
    __asm_movaps(v3);
    __asm_movaps(v3);
    function_2130();
    function_2140();
    function_2130();
    _Z3fooii((int32_t)&g1, (int32_t)&g1);
    function_21f0();
    function_2140();
    function_2130();
    _Z3fooii((int32_t)&g1, (int32_t)&g1);
    function_21f0();
    function_2140();
    function_2130();
    _Z7encryptPii(&g1, (int32_t)&g1);
    function_21f0();
    function_2140();
    function_2130();
    _Z5test2i((int32_t)&g1);
    function_21f0();
    function_2140();
    function_2130();
    _Z15controlFlowTesti((int32_t)&g1);
    function_21f0();
    function_2140();
    function_2130();
    function_2210();
    _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC2IS3_EEPKcRKS3_((char *)&g1, &g1);
    _Z5test3NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE((int32_t)&g1);
    function_2110();
    function_2140();
    function_20b0();
    function_20b0();
    function_2160();
    function_2130();
    _Z5test4iii((int32_t)&g1, (int32_t)&g1, (int32_t)&g1);
    function_21f0();
    function_2140();
    function_2130();
    _Z5test5iii((int32_t)&g1, (int32_t)&g1, (int32_t)&g1);
    function_21f0();
    function_2140();
    _Z8test_strv();
    return -1;
}

// Address range: 0x2fcd - 0x2fe1
int32_t function_2fcd(void) {
    // 0x2fcd
    int32_t v1; // 0x2fcd
    *(int32_t *)(v1 - 160) = v1 - 1;
    *(int32_t *)(v1 - 164) = v1 - 1;
    return function_301c();
}

// Address range: 0x2fe1 - 0x2ff5
int32_t function_2fe1(void) {
    // 0x2fe1
    int32_t v1; // 0x2fe1
    int32_t result = v1 - 1; // 0x2fe6
    *(int32_t *)(v1 - 160) = v1 - 1;
    *(int32_t *)(v1 - 164) = result;
    return result;
}

// Address range: 0x2ff5 - 0x3010
int32_t function_2ff5(void) {
    // 0x2ff5
    int32_t v1; // 0x2ff5
    *(int32_t *)(v1 - 160) = v1 - 1;
    *(int32_t *)(v1 - 164) = v1 - 1;
    return function_20b0();
}

// Address range: 0x301c - 0x3059
int32_t function_301c(void) {
    // 0x301c
    function_2160();
    int32_t v1; // 0x301c
    return function_2200() - 1 & -256 | (uint32_t)v1 / 256 % 256;
}

// Address range: 0x3073 - 0x3074
int32_t function_3073(void) {
    // 0x3073
    int32_t result; // 0x3073
    return result;
}

// Address range: 0x30a2 - 0x30a5
int32_t function_30a2(void) {
    // 0x30a2
    int32_t result; // 0x30a2
    return result;
}

// Address range: 0x30ae - 0x30b8
int32_t function_30ae(void) {
    // 0x30ae
    return function_3073();
}

// Address range: 0x30b8 - 0x30b9
int32_t function_30b8(void) {
    // 0x30b8
    int32_t result; // 0x30b8
    return result;
}

// Address range: 0x30c0 - 0x313f
int32_t function_30c0(void) {
    // 0x30c0
    int32_t v1; // 0x30c0
    int32_t v2 = v1;
    *(char *)v2 = (char)v2 ^ -95;
    char * v3 = (char *)(v2 + 1); // 0x30c6
    *v3 = *v3 ^ -33;
    char * v4 = (char *)(v2 + 2); // 0x30ce
    *v4 = *v4 ^ -65;
    char * v5 = (char *)(v2 + 3); // 0x30d6
    *v5 = *v5 ^ 13;
    char * v6 = (char *)(v2 + 4); // 0x30de
    *v6 = *v6 ^ -52;
    char * v7 = (char *)(v2 + 5); // 0x30e6
    *v7 = *v7 ^ -66;
    char * v8 = (char *)(v2 + 6); // 0x30ee
    *v8 = *v8 ^ 3;
    char * v9 = (char *)(v2 + 7); // 0x30f6
    *v9 = *v9 ^ 12;
    char * v10 = (char *)(v2 + 8); // 0x30fe
    *v10 = *v10 ^ 59;
    char * v11 = (char *)(v2 + 9); // 0x3106
    *v11 = *v11 ^ -115;
    char * v12 = (char *)(v2 + 10); // 0x310e
    *v12 = *v12 ^ -74;
    char * v13 = (char *)(v2 + 11); // 0x3116
    *v13 = *v13 ^ 22;
    char * v14 = (char *)(v2 + 12); // 0x311e
    *v14 = *v14 ^ -80;
    char * v15 = (char *)(v2 + 13); // 0x3126
    *v15 = *v15 ^ 115;
    char * v16 = (char *)(v2 + 14); // 0x312e
    *v16 = *v16 ^ -82;
    char * v17 = (char *)(v2 + 15); // 0x3136
    unsigned char v18 = *v17 ^ 11; // 0x3139
    *v17 = v18;
    return v1 & -256 | (int32_t)v18;
}

// Address range: 0x3140 - 0x314f
int32_t function_3140(void) {
    // 0x3140
    int32_t v1; // 0x3140
    int32_t v2 = v1;
    *(char *)v2 = (char)v2 ^ 11;
    char * v3 = (char *)(v2 + 1); // 0x3146
    unsigned char v4 = *v3 ^ 70; // 0x3149
    *v3 = v4;
    return v1 & -256 | (int32_t)v4;
}

// Address range: 0x3150 - 0x315f
int32_t function_3150(void) {
    // 0x3150
    int32_t v1; // 0x3150
    int32_t v2 = v1;
    *(char *)v2 = (char)v2 ^ 52;
    char * v3 = (char *)(v2 + 1); // 0x3156
    unsigned char v4 = *v3 ^ 5; // 0x3159
    *v3 = v4;
    return v1 & -256 | (int32_t)v4;
}

// Address range: 0x3160 - 0x3187
int32_t function_3160(void) {
    // 0x3160
    int32_t v1; // 0x3160
    int32_t v2 = v1;
    *(char *)v2 = (char)v2 ^ 2;
    char * v3 = (char *)(v2 + 1); // 0x3166
    *v3 = *v3 ^ 76;
    char * v4 = (char *)(v2 + 2); // 0x316e
    *v4 = *v4 ^ -60;
    char * v5 = (char *)(v2 + 3); // 0x3176
    *v5 = *v5 ^ 84;
    char * v6 = (char *)(v2 + 4); // 0x317e
    unsigned char v7 = *v6 ^ -10; // 0x3181
    *v6 = v7;
    return v1 & -256 | (int32_t)v7;
}

// Address range: 0x3190 - 0x31c7
int32_t function_3190(void) {
    // 0x3190
    int32_t v1; // 0x3190
    int32_t v2 = v1;
    *(char *)v2 = (char)v2 ^ 47;
    char * v3 = (char *)(v2 + 1); // 0x3196
    *v3 = *v3 ^ -54;
    char * v4 = (char *)(v2 + 2); // 0x319e
    *v4 = *v4 ^ -52;
    char * v5 = (char *)(v2 + 3); // 0x31a6
    *v5 = *v5 ^ 2;
    char * v6 = (char *)(v2 + 4); // 0x31ae
    *v6 = *v6 ^ -38;
    char * v7 = (char *)(v2 + 5); // 0x31b6
    *v7 = *v7 ^ 119;
    char * v8 = (char *)(v2 + 6); // 0x31be
    unsigned char v9 = *v8 ^ 31; // 0x31c1
    *v8 = v9;
    return v1 & -256 | (int32_t)v9;
}

// Address range: 0x31d0 - 0x3258
// Demangled:     std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string<std::allocator<char> >(char const*, std::allocator<char> const&)
int32_t _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC2IS3_EEPKcRKS3_(char * a1, int32_t * a2) {
    // 0x31d0
    function_20e0();
    function_2150();
    int32_t v1; // 0x31d0
    if (v1 != 0) {
        // 0x3208
        _ZNSt11char_traitsIcE6lengthEPKc((char *)&g1);
    }
    // 0x3237
    _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPKcEEvT_S8_St20forward_iterator_tag((char *)&g1, (char *)&g1, (int32_t)&g1);
    return (int32_t)&g1 - 1;
}

// Address range: 0x3275 - 0x3278
int32_t function_3275(void) {
    // 0x3275
    int32_t result; // 0x3275
    return result;
}

// Address range: 0x3280 - 0x32ab
// Demangled:     bool std::operator==<char, std::char_traits<char>, std::allocator<char> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*)
bool _ZSteqIcSt11char_traitsIcESaIcEEbRKNSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_(int32_t * a1, char * a2) {
    // 0x3280
    return function_2060() != 0;
}

// Address range: 0x32b0 - 0x3330
// Demangled:     std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
int32_t _ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EERKS8_SA_(int32_t * a1, int32_t * a2) {
    // 0x32b0
    function_2080();
    function_2230();
    int32_t v1; // 0x32b0
    return v1 - 2;
}

// Address range: 0x3330 - 0x3372
// Demangled:     std::char_traits<char>::length(char const*)
int32_t _ZNSt11char_traitsIcE6lengthEPKc(char * a1) {
    // 0x3330
    return function_2090() - 2;
}

// Address range: 0x3380 - 0x3490
// Demangled:     void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag)
void _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPKcEEvT_S8_St20forward_iterator_tag(char * a1, char * a2, int32_t a3) {
    // 0x3380
    int32_t v1; // 0x3380
    if (!((v1 == v1 + 1 | !_ZN9__gnu_cxx17__is_null_pointerIKcEEbPT_((char *)&g1)))) {
        // 0x33b5
        function_20d0();
    }
    int32_t v2 = _ZSt8distanceIPKcENSt15iterator_traitsIT_E15difference_typeES3_S3_((char *)&g1, (char *)&g1); // 0x33c9
    if (v2 >= 17) {
        // 0x33d9
        function_2220();
        function_20f0();
        function_2240();
    }
    // 0x3403
    function_2170();
    function_2180();
    function_20c0();
}

// Address range: 0x3490 - 0x34ab
// Demangled:     std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Alloc_hider::~_Alloc_hider()
int32_t _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_Alloc_hiderD2Ev(void) {
    // 0x3490
    return function_2040() - 1;
}

// Address range: 0x34b0 - 0x34f9
// Demangled:     __gnu_cxx::char_traits<char>::length(char const*)
int32_t _ZN9__gnu_cxx11char_traitsIcE6lengthEPKc(char * a1) {
    int32_t result = 0; // 0x34bd
    uint32_t v1 = _ZN9__gnu_cxx11char_traitsIcE2eqERKcS3_((char *)&g1, (char *)&g1); // 0x34d4
    result--;
    while (v1 % 2 == 0) {
        // 0x34c4
        v1 = _ZN9__gnu_cxx11char_traitsIcE2eqERKcS3_((char *)&g1, (char *)&g1);
        result--;
    }
    // 0x34ef
    return result;
}

// Address range: 0x3500 - 0x3523
// Demangled:     __gnu_cxx::char_traits<char>::eq(char const&, char const&)
int32_t _ZN9__gnu_cxx11char_traitsIcE2eqERKcS3_(char * a1, char * a2) {
    // 0x3500
    int32_t v1; // 0x3500
    int32_t v2 = (0x1000000 * v1 >> 24) - 1; // 0x3513
    return v2 & -256 | (int32_t)(v2 == 0x1000000 * v1 >> 24);
}

// Address range: 0x3530 - 0x3544
// Demangled:     bool __gnu_cxx::__is_null_pointer<char const>(char const*)
bool _ZN9__gnu_cxx17__is_null_pointerIKcEEbPT_(char * a1) {
    // 0x3530
    int32_t v1; // 0x3530
    return v1 == 0;
}

// Address range: 0x3550 - 0x358c
// Demangled:     std::iterator_traits<char const*>::difference_type std::distance<char const*>(char const*, char const*)
int32_t _ZSt8distanceIPKcENSt15iterator_traitsIT_E15difference_typeES3_S3_(char * a1, char * a2) {
    // 0x3550
    _ZSt19__iterator_categoryIPKcENSt15iterator_traitsIT_E17iterator_categoryERKS3_((char **)&g1);
    int32_t v1 = _ZSt10__distanceIPKcENSt15iterator_traitsIT_E15difference_typeES3_S3_St26random_access_iterator_tag((char *)&g1, (char *)&g1, (int32_t)&g1); // 0x3581
    return v1 - 1;
}

// Address range: 0x3590 - 0x359e
int32_t __clang_call_terminate(void) {
    // 0x3590
    function_2070();
    return function_2050();
}

// Address range: 0x35a0 - 0x35b9
// Demangled:     std::iterator_traits<char const*>::difference_type std::__distance<char const*>(char const*, char const*, std::random_access_iterator_tag)
int32_t _ZSt10__distanceIPKcENSt15iterator_traitsIT_E15difference_typeES3_S3_St26random_access_iterator_tag(char * a1, char * a2, int32_t a3) {
    // 0x35a0
    int32_t v1; // 0x35a0
    return -2 - v1 + v1;
}

// Address range: 0x35c0 - 0x35ca
// Demangled:     std::iterator_traits<char const*>::iterator_category std::__iterator_category<char const*>(char const* const&)
int32_t _ZSt19__iterator_categoryIPKcENSt15iterator_traitsIT_E17iterator_categoryERKS3_(char ** a1) {
    // 0x35c0
    int32_t v1; // 0x35c0
    return v1 - 2;
}

// Address range: 0x35cc - 0x35d9
int32_t _fini(void) {
    // 0x35cc
    int32_t v1; // 0x35cc
    return v1 - 2;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (11.4.0)
// Detected functions: 85

